repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    exclude: generated

- repo: https://github.com/PyCQA/flake8
  rev: 3.7.9
  hooks:
  - id: flake8

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.3
  hooks:
    - id: shellcheck
